function State(argument0, argument1, argument2, argument3) constructor //State
{
    if (argument3 == undefined)
        argument3 = 0
    id = argument0
    name = argument1
    script = ((!is_undefined(argument2)) ? method(other, argument2) : undefined)
    flags = argument3
    other.statemachine[id] = self
}

function scr_definestates() //scr_definestates
{
    new State((0 << 0), "Normal", scr_player_normal)
    new State((1 << 0), "Tumble", scr_player_tumble)
    new State((2 << 0), "FinishingBlow", scr_player_finishingblow)
    new State((3 << 0), "Ejected", scr_player_ejected)
    new State((4 << 0), "Fireass", scr_player_fireass)
    new State((5 << 0), "Firemouth", scr_player_firemouth)
    new State((6 << 0), "Titlescreen", scr_player_titlescreen)
    new State((7 << 0), "TackleCharge", scr_player_tacklecharge)
    new State((8 << 0), "Cheeseball", scr_player_cheeseball)
    new State((9 << 0), "CheesePep", scr_player_cheesepep)
    new State((10 << 0), "CheesePepStick", scr_player_cheesepepstick)
    new State((11 << 0), "BoxxedPep", scr_player_boxxedpep)
    new State((12 << 0), "ClimbWall", scr_player_climbwall)
    new State((13 << 0), "KnightPepSlopes", scr_player_knightpepslopes)
    new State((14 << 0), "Portal", scr_player_portal)
    new State((15 << 0), "ChainsawBump", scr_player_chainsawbump)
    new State((16 << 0), "SuplexGrab", scr_player_suplexgrab)
    new State((17 << 0), "GotTreasure", scr_player_gottreasure)
    new State((18 << 0), "KnightPep", scr_player_knightpep)
    new State((19 << 0), "BombPep", scr_player_bombpep)
    new State((20 << 0), "ChainsawPogo", scr_player_chainsawpogo)
    new State((21 << 0), "Stunned", scr_player_stunned)
    new State((22 << 0), "Chainsaw", scr_player_chainsaw)
    new State((23 << 0), "MachRoll", scr_player_machroll)
    new State((24 << 0), "Shotgun", scr_player_shotgun)
    new State((25 << 0), "SuperSlam", scr_player_superslam)
    new State((26 << 0), "Skateboard", scr_player_skateboard)
    new State((27 << 0), "Grind", scr_player_grind)
    new State((28 << 0), "Grab", scr_player_grab)
    new State((29 << 0), "Punch", scr_player_punch)
    new State((30 << 0), "Shoulder", scr_player_shoulder)
    new State((31 << 0), "Backbreaker", scr_player_backbreaker)
    new State((32 << 0), "BossIntro", scr_player_bossintro)
    new State((33 << 0), "Ejected2", scr_player_ejected)
    new State((34 << 0), "KeyGet", scr_player_keyget)
    new State((35 << 0), "Tackle", scr_player_tackle)
    new State((36 << 0), "Jump", scr_player_jump)
    new State((37 << 0), "Ladder", scr_player_ladder)
    new State((38 << 0), "SlipNSlide", scr_player_slipnslide)
    new State((39 << 0), "ComingOutDoor", scr_player_comingoutdoor)
    new State((40 << 0), "SJump", scr_player_Sjump)
    new State((41 << 0), "Victory", scr_player_victory)
    new State((42 << 0), "SJumpPrep", scr_player_Sjumpprep)
    new State((43 << 0), "Crouch", scr_player_crouch)
    new State((44 << 0), "CrouchJump", scr_player_crouchjump)
    new State((45 << 0), "CrouchSlide", scr_player_crouchslide)
    new State((46 << 0), "Mach1", scr_player_mach1)
    new State((47 << 0), "Mach2", scr_player_mach2)
    new State((48 << 0), "MachSlide", scr_player_machslide)
    new State((49 << 0), "Bump", scr_player_bump)
    new State((50 << 0), "Hurt", scr_player_hurt)
    new State((51 << 0), "FreeFall", scr_player_freefall)
    new State((52 << 0), "Hang", scr_player_hang)
    new State((53 << 0), "FreeFallLand", scr_player_freefallland)
    new State((54 << 0), "Door", scr_player_door)
    new State((55 << 0), "BarrelBounce", scr_player_barrelbounce)
    new State((56 << 0), "BarrelCrouch", scr_player_barrelcrouch)
    new State((57 << 0), "BarrelFloat", scr_player_barrelfloat)
    new State((58 << 0), "BarrelMach2", scr_player_barrelmach2)
    new State((59 << 0), "BarrelMach1", scr_player_barrelmach1)
    new State((60 << 0), "BarrelFall", scr_player_barrelfall)
    new State((61 << 0), "BarrelNormal", scr_player_barrelnormal)
    new State((62 << 0), "BarrelSlipNSlide", scr_player_barrelslipnslide)
    new State((63 << 0), "BarrelRoll", scr_player_barrelroll)
    new State((64 << 0), "Current", scr_player_current)
    new State((65 << 0), "Boulder", scr_player_boulder)
    new State((66 << 0), "Mach3", scr_player_mach3)
    new State((67 << 0), "FreeFallPrep", scr_player_freefallprep)
    new State((68 << 0), "SJumpLand", scr_player_Sjumpland)
    new State((69 << 0), "SlapDash", scr_player_slapdash)
    new State((70 << 0), "Parry", scr_player_parry)
    new State((71 << 0), "Breakdance", scr_player_breakdance)
    new State((72 << 0), "Flustered", scr_player_flustered)
    new State((73 << 0), "Shoulderbash", scr_player_shoulderbash)
    new State((74 << 0), "GunShoot", scr_player_gunshoot)
    new State((75 << 0), "Shoryuken", scr_player_shoryuken)
    new State((76 << 0), "Pipe", scr_player_pipe)
    new State((77 << 0), "Faceplant", scr_player_faceplant)
    new State((78 << 0), "Ghost", scr_player_ghost)
    new State((79 << 0), "Golf", scr_player_golf)
    new State((80 << 0), "Thok", scr_player_thok)
    new State((81 << 0), "Pogo", scr_player_pogo)
    new State((82 << 0), "Wait", scr_player_wait)
    new State((83 << 0), "Handstand", scr_player_handstand)
    new State((84 << 0), "SideJumpPrep", scr_player_sidejumpprep)
    new State((85 << 0), "SideJump", scr_player_sidejump)
    new State((86 << 0), "Grow", scr_player_grow)
    new State((87 << 0), "Hitstun", scr_player_hitstun, (1 << 0))
    new State((88 << 0), "SlipBanan", scr_player_slipbanan)
    new State((89 << 0), "Taxi", scr_player_taxi)
    new State((90 << 0), "BallLOL", scr_player_balllol)
    new State((91 << 0), "KungFu", scr_player_kungfu)
    new State((92 << 0), "TackleOLD", scr_player_tackleold)
    new State((93 << 0), "GameOver", scr_player_gameover)
    new State((94 << 0), "TimesUp!", scr_player_timesup)
    new State((95 << 0), "Ramp", scr_player_ramp)
    new State((96 << 0), "WeenieMount", scr_player_weeniemount)
    new State((97 << 0), "FireMove", scr_player_firemove)
    new State((98 << 0), "PitFall", scr_player_pitfall)
    new State((99 << 0), "HeroPep", scr_player_heropep)
    new State((100 << 0), "HomingAttack", scr_playerS_homingattack)
    new State((101 << 0), "Pinch", scr_player_pinch)
    new State((102 << 0), "Start", scr_player_start)
    new State((103 << 0), "SwingDingFinish", scr_player_swingdingfinish)
    new State((104 << 0), "Seat", scr_player_seat)
    new State((105 << 0), "Barrel", scr_player_barrel)
    new State((106 << 0), "SmallPep", scr_player_smallpep)
    new State((107 << 0), "SmallPepDash", scr_player_smallpepdash)
    new State((108 << 0), "#RETRODeath", scr_player_RETROdeath)
    new State((109 << 0), "Firework", scr_player_firework)
    new State((110 << 0), "Nothing...", undefined)
    new State((111 << 0), "LevelSelect", scr_player_levelselect)
    new State((112 << 0), "Cheeseslime", scr_playerC_normal)
    new State((113 << 0), "CheeseslimeAttack", scr_playerC_attack)
    new State((114 << 0), "Actor", scr_player_actor)
    new State((115 << 0), "KnightPepBump", scr_player_knightpepbump)
    new State((116 << 0), "SecretPortal", undefined)
    new State((117 << 0), "Held", scr_player_held)
    new State((118 << 0), "Lunge", scr_player_lunge)
    new State((119 << 0), "KungFuGrab", scr_player_kungfugrab)
    new State((120 << 0), "NWallJump", scr_playerN_walljump)
    new State((121 << 0), "KingBubble", scr_player_kingbubble)
    new State((122 << 0), "NPCLocked", scr_player_npclocked)
    new State((123 << 0), "ForcedFall", scr_player_forcedfall)
    new State((124 << 0), "BombKnockback", scr_player_bombknockback)
    new State((125 << 0), "HubEject", scr_player_hubeject)
    new State((126 << 0), "SageLevelEntrance", scr_player_sagelevelentrance)
    new State((127 << 0), "GateCutscene", scr_player_gatecutscene)
    new State((128 << 0), "NoClip", scr_player_noclip)
}

